language: python
sudo: false
python:
  - '3.5'
env:
  matrix:
    - TOXENV=py34-django19
    - TOXENV=py35-django19
    - TOXENV=py34-django110
    - TOXENV=py35-django110
    - TOXENV=py35-flake8
install:
  - pip install tox
script:
  - tox -e $TOXENV
