language: python
sudo: false
python:
  - '3.5'
env:
  - TOXENV=py34-django19
  - TOXENV=py35-django19
  - TOXENV=py34-django110
  - TOXENV=py35-django110
  - TOXENV=py34-django111
  - TOXENV=py35-django111
  - TOXENV=py35-flake8
matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36-django111
install:
  - pip install tox
script:
  - tox -e $TOXENV
