language: python
sudo: false
python:
  - '3.4'
  - '3.5'
  - '3.6'
env:
  - DJANGO_VERSION='1.11,<2.0'
  - DJANGO_VERSION='2.0,<2.1'
  - DJANGO_VERSION='2.1,<2.2'
matrix:
  exclude:
    - env: DJANGO_VERSION='2.1,<2.2'
      python: '3.4'
jobs:
  include:
    - stage: flake8
      python: '3.6'
      script: flake8 skivvy tests
install:
  - pip install -r requirements.txt
  - pip install "django>=$DJANGO_VERSION"
  - python3 -m django --version
script:
  - py.test
